config/routes.rb
Rails.application.routes.draw do
  get 'dessert/index'
  get 'food/index'
  
  devise_for :users
  resources :books
  resources :educations
  resources :profiles
  resources :users

  root to: "users#index"
  
  resources :restaurants, only: [:index]
  
 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  #devise :database_authenticatable, :registerable,
        # :rememberable, :validatable
    #validates :identifier, presence: true, on: create

    #has_one :profile
    #has_one :education 
    #has_many :books

   # scope :by_book_year, ->(year) {joins(:books).where(books: {year: year})}

before_validation :generate_id


private

def generate_id
    self.identifier = "ABC-#{Date.today.year}-#{SecureRandom.hex(5)}"
end
def self.generate_number
    SecureRandom.hex(10)
end

def generate_number_from_user
    username + SecureRandom.hex(10)
end
def self.full_name
    self.second.name + self.second.username
end
def self.location
    email
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def del
    @user.destroy
    @user = user.find(params[:id])
    redirect_to users_url, notice: "user was successfully destroyed."
    end
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :username, :email)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Username:</strong>
    <%= user.username %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<%= link_to "logout", destroy_user_session_path(@user), data: { 'turbo-method': :delete, 'turbo-confirm': 'Are you sure?' } %>
<%= button_to "Sign out", destroy_user_session_path, method: :delete, form: { data: { turbo_confirm: "Are you sure?" } } %>

<h1>Users</h1>

<%= user_signed_in? %>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col"> name</th>
      <th scope="col">username</th>
      <th scope="col">email</th>
      <th scope="col">identifier</th>
      <th scope="col">action</th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user|%>
    <tr>
      <th scope="row"><%= user.id%></th>
      <td><%= user.name %></td>
      <td><%= user.username %></td>
      <td><%= user.email%></td>
      <td><%= user.identifier%></td>
      <td><%= link_to 'show', user_path(user.id), class:"btn btn-primary btn-sm"%></td>
    </tr>
    <% end %>
  </tbody>
</table>


<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>