config/routes.rb
Rails.application.routes.draw do
  get 'dessert/index'
  get 'food/index'
  
  devise_for :users
  resources :books
  resources :educations
  resources :profiles
  resources :users

  root to: "users#index"
  
  resources :restaurants, only: [:index]
  
 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/education.rb
class Education < ApplicationRecord
    belongs_to :user
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
  before_action :set_education, only: %i[ show edit update destroy ]

  # GET /educations or /educations.json
  def index
    @educations = Education.all
  end

  # GET /educations/1 or /educations/1.json
  def show
  end

  # GET /educations/new
  def new
    @education = Education.new
  end

  # GET /educations/1/edit
  def edit
  end

  # POST /educations or /educations.json
  def create
    @education = Education.new(education_params)

    respond_to do |format|
      if @education.save
        format.html { redirect_to education_url(@education), notice: "Education was successfully created." }
        format.json { render :show, status: :created, location: @education }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /educations/1 or /educations/1.json
  def update
    respond_to do |format|
      if @education.update(education_params)
        format.html { redirect_to education_url(@education), notice: "Education was successfully updated." }
        format.json { render :show, status: :ok, location: @education }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /educations/1 or /educations/1.json
  def destroy
    @education.destroy

    respond_to do |format|
      format.html { redirect_to educations_url, notice: "Education was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_education
      @education = Education.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def education_params
      params.require(:education).permit(:user_id, :university, :stage)
    end
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/views/educations/_education.html.erb
<div id="<%= dom_id education %>">
  <p>
    <strong>User:</strong>
    <%= education.user_id %>
  </p>

  <p>
    <strong>University:</strong>
    <%= education.university %>
  </p>

  <p>
    <strong>Stage:</strong>
    <%= education.stage %>
  </p>

</div>

app/views/educations/_form.html.erb
<%= form_with(model: education) do |form| %>
  <% if education.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(education.errors.count, "error") %> prohibited this education from being saved:</h2>

      <ul>
        <% education.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.select :user_id, User.all.pluck(:name,:id)%>
  </div>

  <div>
    <%= form.label :university, style: "display: block" %>
    <%= form.text_field :university %>
  </div>

  <div>
    <%= form.label :stage, style: "display: block" %>
    <%= form.text_field :stage %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/educations/edit.html.erb
<h1>Editing education</h1>

<%= render "form", education: @education %>

<br>

<div>
  <%= link_to "Show this education", @education %> |
  <%= link_to "Back to educations", educations_path %>
</div>

app/views/educations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Educations</h1>

<div id="educations">
  <% @educations.each do |education| %>
    <%= render education %>
    <p>
      <%= link_to "Show this education", education %>
    </p>
  <% end %>
</div>

<%= link_to "New education", new_education_path %>

app/views/educations/new.html.erb
<h1>New education</h1>

<%= render "form", education: @education %>

<br>

<div>
  <%= link_to "Back to educations", educations_path %>
</div>

app/views/educations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @education %>

<div>
  <%= link_to "Edit this education", edit_education_path(@education) %> |
  <%= link_to "Back to educations", educations_path %>

  <%= button_to "Destroy this education", @education, method: :delete %>
</div>